import { expect, test } from '@playwright/test'

test('persists the accessible sound toggle without reserving mobile arena space', async ({ page, isMobile }) => {
  const errors: string[] = []
  const sounds: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  page.on('request', (request) => { if (request.url().includes('/sounds/')) sounds.push(request.url()) })
  await page.goto('/')
  await expect(page.getByRole('button', { name: 'Play', exact: true })).toBeVisible()
  expect(sounds).toEqual([])
  await page.getByRole('button', { name: 'Play', exact: true }).click()
  await expect(page.locator('.game-canvas canvas')).toBeVisible()
  const mute = page.getByRole('button', { name: 'Mute sound', exact: true })
  await expect(mute).toHaveAttribute('aria-pressed', 'false')
  const rect = await mute.boundingBox()
  expect(rect!.width).toBeGreaterThanOrEqual(44)
  expect(rect!.height).toBeGreaterThanOrEqual(44)
  await expect(mute.locator('svg')).toHaveAttribute('aria-hidden', 'true')
  await expect(mute.locator('svg')).toHaveCSS('pointer-events', 'none')
  if (isMobile) expect((await page.locator('.game-canvas').boundingBox())!.y).toBe(0)
  const canvas = await page.locator('.game-canvas canvas').elementHandle()
  await mute.click()
  await expect(page.getByRole('button', { name: 'Unmute sound', exact: true })).toHaveAttribute('aria-pressed', 'true')
  expect(await page.evaluate(() => localStorage.getItem('pirate-battle:sound-muted'))).toBe('true')
  // Alternar áudio não remonta o PixiJS nem troca o canvas atual.
  expect(await canvas!.evaluate((element) => element === document.querySelector('.game-canvas canvas'))).toBe(true)
  await page.getByRole('button', { name: 'Pause', exact: true }).click()
  await page.getByRole('button', { name: 'Resume', exact: true }).click()
  await page.reload()
  await page.getByRole('button', { name: 'Play', exact: true }).click()
  const unmute = page.getByRole('button', { name: 'Unmute sound', exact: true })
  await expect(unmute).toHaveAttribute('aria-pressed', 'true')
  await unmute.click()
  await expect(page.getByRole('button', { name: 'Mute sound', exact: true })).toHaveAttribute('aria-pressed', 'false')
  expect(await page.evaluate(() => localStorage.getItem('pirate-battle:sound-muted'))).toBe('false')
  await page.getByRole('button', { name: 'Exit game', exact: true }).click()
  await page.getByRole('button', { name: 'Play', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Mute sound', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Exit game', exact: true }).click()
  expect(errors).toEqual([])
})

test('keeps playing when browser audio activation is rejected', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  // Simulamos a política do navegador sem tentar medir saída de áudio.
  await page.addInitScript(() => {
    Object.defineProperty(AudioContext.prototype, 'state', { get: () => 'suspended' })
    AudioContext.prototype.resume = () => Promise.reject(new DOMException('Blocked by browser', 'NotAllowedError'))
  })
  await page.goto('/')
  await page.getByRole('button', { name: 'Play', exact: true }).click()
  await expect(page.locator('.game-canvas canvas')).toBeVisible()
  await page.keyboard.down('Space')
  await page.waitForTimeout(400)
  await page.keyboard.up('Space')
  await page.getByRole('button', { name: 'Pause', exact: true }).click()
  await page.getByRole('button', { name: 'Resume', exact: true }).click()
  await page.getByRole('button', { name: 'Mute sound', exact: true }).click()
  await page.getByRole('button', { name: 'Unmute sound', exact: true }).click()
  await page.getByRole('button', { name: 'Exit game', exact: true }).click()
  expect(errors).toEqual([])
})

test('keeps the game usable when the ten WAV files are unavailable', async ({ page }) => {
  const errors: string[] = []
  const failed = new Set<string>()
  page.on('pageerror', (error) => errors.push(error.message))
  await page.context().route(/\/assets\/pirate-battle\/sounds\//, (route) => {
    failed.add(new URL(route.request().url()).pathname)
    return route.fulfill({ status: 404, body: '' })
  })
  await page.goto('/')
  await expect(page.getByRole('button', { name: 'Play', exact: true })).toBeVisible()
  const network = await page.context().newCDPSession(page)
  await network.send('Network.setBypassServiceWorker', { bypass: true })
  await page.getByRole('button', { name: 'Play', exact: true }).click()
  await expect.poll(() => failed.size).toBe(10)
  await expect(page.locator('.game-canvas canvas')).toBeVisible()
  await page.getByRole('button', { name: 'Mute sound', exact: true }).click()
  await page.getByRole('button', { name: 'Pause', exact: true }).click()
  await page.getByRole('button', { name: 'Resume', exact: true }).click()
  await page.getByRole('button', { name: 'Exit game', exact: true }).click()
  expect(errors).toEqual([])
})
